# base on latest python image
FROM python:latest

# add our python program
ADD collector.py requirements.txt infofile.py data_vars.py ./

# install dependent libraries
RUN pip install -r requirements.txt

# the command to run our program
CMD ["python",  "-u", "./collector.py"]


