services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbit
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  consumer:
    build: consumer/.
    networks:
      - rabbit
    deploy:
      mode: replicated
      replicas: 4 #how many?
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
  producer:
    build: producer/.
    networks:
      - rabbit
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  collector_plotter:
    build: collector_plotter/.
    networks:
      - rabbit
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    volumes: 
      - /mnt/c/Users/nicol/OneDrive - University of Bristol/soft_eng/hzz_cloud_tech/collector_plotter:/app
      - /mnt/c/Users/nicol/OneDrive - University of Bristol/soft_eng/hzz_cloud_tech/output_plots:/app/output

networks:
  rabbit:
    driver: bridge #or bridge?
    attachable: true

