apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      volumes:
      - name: collector-storage
        persistentVolumeClaim:  
          claimName: shared-pvc
      containers:
      - name: collector
        image: collector-image
        imagePullPolicy: Never
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq
        volumeMounts:
        - mountPath: "/app/output"
          name: collector-storage






