apiVersion: batch/v1
kind: Job
metadata:
  name: manager
  labels: 
    app: manager
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: manager
    spec:
      restartPolicy: Never
      containers:
      - name: manager
        image: manager-image
        imagePullPolicy: Never
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq



